name: .NET Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100

    - name: Restore dependencies
      run: dotnet restore json-patch-generator.sln

    - name: Build
      run: dotnet build json-patch-generator.sln --no-restore

    - name: Test
      run: dotnet test json-patch-generator.sln --no-build --verbosity normal

    - name: Publish Package
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: src/JsonPatchGenerator/JsonPatchGenerator.csproj
         NUGET_KEY: ${{secrets.FIREBEND_NUGET_KEY}}
         TAG_COMMIT: false
