name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
  
    - name: Restore dependencies
      run: dotnet json-patch-generator.sln restore
      
    - name: Build
      run: dotnet json-patch-generator.sln build --no-restore
      
    - name: Test
      run: dotnet json-patch-generator.sln test --no-build --verbosity normal
